### ISSUE TITLE
[BUG] Single User Endpoint does not return email when it is in the schema AND database

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#274] opened 2024-08-23 12:46 UTC
### Current behavior

Currently when getting a single user via the API spec, the email of the user is not returned.

### Desired behavior

In this situation, I expected the endpoint to return the email

### API Route

GET /users/{id}

### Steps to reproduce

1. Go to the Swagger
2. Authenticate yourself
3. Go to the GET /users/{id} endpoint
4. Get a user with email in the database
5. Observe the email not being returned.

**Comment by Yoronex** [comment] 2024-08-23 14:14
Duplicate of https://github.com/GEWIS/sudosos-backend/issues/138

**Closed by Yoronex** 2024-08-23 14:14 UTC
Labels: Status: Triage, Type: Bug
