### ISSUE TITLE
[BUG] Invoice edit returns 500 bad request if invoice is paid

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#327] opened 2024-09-17 12:53 UTC
### Current behavior

When patching an invoice, in this case it's settings, the backend returns a 500 if the invoice is paid.

### Desired behavior

I expected to either be able to edit the invoice, or get a different error code. 

### API Route

PATCH /invoices/{id}

### Steps to reproduce

I went to invoice 132, patched the description, got 500 back.

### Logs and Error Messages

 [2024-09-17T14:47:26.312] [ERROR] InvoiceController - Could not update invoice: TypeError: Cannot read properties of undefined (reading 'id')

2024-09-17T12:47:26.369878284Z 4|http-worker  |     at Function.asBaseInvoiceResponse (/app/src/service/invoice-service.ts:133:19)

2024-09-17T12:47:26.369950741Z 4|http-worker  |     at InvoiceController.updateInvoice (/app/src/controller/invoice-controller.ts:290:31)

2024-09-17T12:47:26.370057152Z 4|http-worker  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)

2024-09-17T12:47:26.370403561Z 4|http-worker  | [2024-09-17T14:47:26.312] [ERROR] InvoiceController - Could not update invoice: TypeError: Cannot read properties of undefined (reading 'id')

2024-09-17T12:47:26.370536737Z 4|http-worker  |     at Function.asBaseInvoiceResponse (/app/src/service/invoice-service.ts:133:19)

2024-09-17T12:47:26.370655218Z 4|http-worker  |     at InvoiceController.updateInvoice (/app/src/controller/invoice-controller.ts:290:31)

2024-09-17T12:47:26.370779581Z 4|http-worker  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)

2024-09-17T12:47:26.959111027Z 0|http-worker  | [2024-09-17T14:47:26.956] [TRACE] InvoiceController - Update Invoice { description: 'SudoSOS debt from IntroductionWeek 2023, Group CS20.' } by user {
...

**Comment by JustSamuel** [comment] 2024-09-18 12:53
By design, if the invoice is paid it has been sent. If the other company already paid your invoice, it would make almost no sense to edit it.

**Comment by JustSamuel** [comment] 2024-09-18 12:54
I agree that the error might be nicer, but that will be fixed in #326, so closing.

**Closed by JustSamuel** 2024-09-18 12:54 UTC
Labels: Status: Triage, Type: Bug
